#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := webradio

DEBUG_FLAGS := -ggdb -g
EXTRA_LDFLAGS := -g -O0

include $(IDF_PATH)/make/project.mk

